### ISSUE TITLE
Send Fleet Command

### ISSUE THREAD

**Issue by yakivyusin** [andrii1812/galcon-server#13]
Protocol Version:
```
[
  {
    "from": [ ] //int (planet id)
    "to": //int (planet id)
  }
]
```

Now server implements "from" field as integer, not array: [link](https://github.com/andrii1812/galcon-server/blob/master/src/Model/SendFleetCommand.cs#L5)

**Comment by ABartkoviak** [comment]
Please, leave comment if the commit resolved an issue.

**Comment by yakivyusin** [comment]
Fixed
