### ISSUE TITLE
Flight in Tick Update

### ISSUE THREAD

**Issue by yakivyusin** [andrii1812/galcon-server#14]
Protocol:
`"owner": //int`

Now:
`"ownerID": //int`
___
Protocol:
`"from": //int`

Now:
`"fromPlanet": //int`
___
Protocol:
`"to": //int`

Now:
`"toPlanet": //int`

**Comment by ABartkoviak** [comment]
Please, leave comment if the commit resolved an issue.

**Comment by yakivyusin** [comment]
Fixed
